config/routes.rb
MongoTools::Application.routes.draw do
  use_doorkeeper

  resources :explorer do
    scope :module => "explorer" do
      resources :collections, :except => [:new], :constraints => { :id => /.*/ } do
        resources :documents
      end
    end
  end

  get "/monitoring" => "monitoring#index"
  get "/monitoring/opcounts" => "monitoring#op_counts"

  get "/sharding" => "sharding#index"

  resources :query_analyzer, :only => [:index]
  root :to => redirect("/explorer")

  resource :server_status, :only => [:index, :show]

  resources :databases, :only => [:index, :show] do
    resource :sharding_stats, :only => [:index, :show]
  end

end

app/views/shared/_collections_breadcrumbs.html.erb
<ul class="breadcrumb">
<% if current_document %>
  <li><%= link_to 'mongotools', root_path %> <span class="divider">/</span></li>
  <li><%= link_to 'explorer', explorer_index_path %> <span class="divider">/</span></li>
  <li><%= link_to current_database_name, explorer_path(current_database_name)%> <span class="divider">/</span></li>
  <li><%= link_to current_collection_name, explorer_collection_path(current_database_name, current_collection_name)%> <span class="divider">/</span></li>
  <li class="active"><%= current_document_id %></li>
<% elsif current_collection %>
  <li><%= link_to 'mongotools', root_path %> <span class="divider">/</span></li>
  <li><%= link_to 'explorer', explorer_index_path %> <span class="divider">/</span></li>
  <li><%= link_to current_database_name, explorer_path(current_database_name) %> <span class="divider">/</span></li>
  <li class="active"><%= current_collection_name %></li>
<% elsif current_database %>
  <li><%= link_to 'mongotools', root_path %> <span class="divider">/</span></li>
  <li><%= link_to 'explorer', explorer_index_path %> <span class="divider">/</span></li>
  <li class="active"><%= current_database_name %></li>
<% elsif explorer_index_path == request.env['PATH_INFO'] %>
  <li><%= link_to 'mongotools', root_path %> <span class="divider">/</span></li>
  <li class="active">explorer</li>
<% else %>
  <li class="active">mongotools</li>
<% end %>
</ul>

app/views/shared/_collections_sidebar.html.erb
<div class="well well-thin sidebar-nav">
  <ul class="nav nav-list">
    <li class="nav-header">Database: <%= current_database_name %></li>
    <li class="divider"></li>
    <li class="nav-header">Collections</li>
    <% current_database.collection_names.sort.select { |c| can_read_collection?(current_database_name, c) }.each do |c| %>
    <li class="<%= current_collection_name == c ? "active" : "" %>"><%= link_to c, explorer_collection_path(current_database_name, c) %></li>
    <% end %>
    <li class="divider"></li>
    <li><%= link_to "All Databases", explorer_index_path %></li>
  </ul>
</div>

app/views/shared/_database_sidebar.html.erb
<div class="well well-thin sidebar-nav">
  <ul class="nav nav-list">
    <li class="nav-header">Databases</li>
    <% all_databases.each do |d| %>
    <li><%= link_to d, explorer_path(d) %></li>
    <% end %>
  </ul>
</div>

app/views/shared/blacklist.html.erb
<% content_for :sidebar do %>
<%= render :partial => "shared/database_sidebar" %>
<% end %>

<div class="alert alert-error">
  <strong>Error!</strong>
  That database is not allowed to be viewed through this interface
</div>

app/views/shared/collection_blacklist.html.erb
<% content_for :sidebar do %>
<%= render :partial => "shared/collections_sidebar" %>
<% end %>

<div class="alert alert-error">
  <strong>Error!</strong>
  Documents in this collection are not allowed to be <%= can_read_collection? && !can_edit_collection? ? "edited" : "viewed" %>
</div>