config/routes.rb
MongoTools::Application.routes.draw do
  use_doorkeeper

  resources :explorer do
    scope :module => "explorer" do
      resources :collections, :except => [:new], :constraints => { :id => /.*/ } do
        resources :documents
      end
    end
  end

  get "/monitoring" => "monitoring#index"
  get "/monitoring/opcounts" => "monitoring#op_counts"

  get "/sharding" => "sharding#index"

  resources :query_analyzer, :only => [:index]
  root :to => redirect("/explorer")

  resource :server_status, :only => [:index, :show]

  resources :databases, :only => [:index, :show] do
    resource :sharding_stats, :only => [:index, :show]
  end

end

app/controllers/explorer/collections_controller.rb
class Explorer::CollectionsController < ExplorerController
  def index
    redirect_to explorer_path(current_database_name)
  end

  def create
    begin
     conn = MongoMapper.connection
     db = conn.db(current_database_name)
     db.create_collection(params[:coll])
     flash[:info] = "The collection was added successfully"
     redirect_to explorer_collection_path(current_database_name, params[:coll] )
    rescue Exception => ex
     flash[:error] = ex.message
    end
  end

  def destroy
    begin
     conn = MongoMapper.connection
     db = conn.db(current_database_name)
     db.drop_collection(current_collection_name)
     flash[:info] = "The collection was removed successfully"
     redirect_to explorer_collections_path(current_database_name)
    rescue Exception => ex
     flash[:error] = ex.message
    end
  end

  def show
    @opts = {}
    #convert string to bool
    @explain = params[:explain] == "true"

    #parse out params
    @query = params[:query] ? Crack::JSON.parse("{#{params[:query]}}") : {}
    @opts[:fields] = params[:fields] ? Crack::JSON.parse("{#{params[:fields]}}") : {}
    @opts[:skip] = params[:skip].to_i
    @opts[:limit] = params[:limit].to_i
    #default range - should notify user if greater than range.
    @opts[:limit] = 25 unless (1..1000).include?(@opts[:limit])

    sort = params[:sort] ? Crack::JSON.parse("{#{params[:sort]}}") : {}
    sort.each_pair { |k,v| sort[k] = (v.to_i == -1) ? Mongo::DESCENDING : Mongo::ASCENDING }
    @opts[:sort] = sort

    @opts.delete_if { |k,v| v.kind_of?(Hash) && v.empty? }
    @opts[:fields].delete("_id") if @opts[:fields] && @opts[:fields].include?("_id")
    @results = current_collection.find(@query, @opts)
    render layout: !request.xhr?
  end

end

app/controllers/explorer/documents_controller.rb
class Explorer::DocumentsController < ExplorerController
  before_filter :require_edit_access, :except => [:index, :show]

  def index
    redirect_to explorer_collection_document_path(current_database_name,
                                                  current_collection_name)
  end

  def show
    if not current_document
      flash[:error] = "That document doesn't exist"
    end
    @doc = current_document
  end

  def create
    coll = current_collection
    #If there's a JSON parsing problem, show the error to user
    #and allow them to try again.
    begin
      json = JSON.parse(params[:query])
      if json.has_key?('_id')
        json["_id"] = BSON::ObjectId(json["_id"])
      end
      coll.insert(json)
      flash[:info] = "created successfully"
      redirect_to explorer_path(current_database_name,
                                current_collection_name)
    rescue Exception => exc
      flash[:error] = exc.message
      @query = params[:query]
      render :action => :new
    end
  end

  def destroy
    begin
      coll = current_collection
      coll.remove({'_id' => BSON::ObjectId(current_document_id)})
      flash[:info] = "deleted successfully"
    rescue Exception => exc
      flash[:error] = exc.message
    end
    redirect_to explorer_collection_path(current_database_name,
                                         current_collection_name)
  end

  def edit
    @query = current_document.to_json
  end

  def new
    new_id = BSON::ObjectId.new
    @query = "{_id: ObjectId(\""+new_id.to_s+"\")}"
  end

  def update
    coll = current_collection
    #If there's a JSON parsing problem, show the error to user
    #and allow them to try again.
    begin
      json = JSON.parse(params[:query])
      id = nil
      if json.has_key?('_id')
        id = BSON::ObjectId(json["_id"])
        json.delete("_id")
      else
        id = BSON::ObjectId(current_document_id)
      end

      coll.update({'_id' => id}, json)
      flash[:info] = "updated successfully"
      redirect_to explorer_collection_document_path(current_database_name,
                                                    current_collection_name)
    rescue Exception => exc
      flash[:error] = exc.message
      @query = params[:query]
      render :action => :edit
    end
  end
end

app/controllers/explorer_controller.rb
require 'rubygems'
require 'mongo'
include Mongo

class ExplorerController < ApplicationController
  before_filter :check_mongo_blacklist

  def index
    respond_to do |format|
      text = "OK"
      if params.has_key?(:db)
        database = MongoMapper.connection.database_names
        for db in database
          if db.casecmp(params[:db]) == 0
            text = "Duplicate"
            break
          end
        end    
      end
      format.json { render json: text}
      format.html 
    end
  end

  def show
  end
  


  def edit
    if params.has_key?(:db)
      if params[:db].empty?
        flash[:error] = "Database name can't be empty.."
        render "explorer/index"
        return
      elsif params[:db].match(/([\/\\\. $])/)
        flash[:error] = "Database name can't have invalid characters."
        render "explorer/index"
        return
      else
        flash[:error]  = false
        database = MongoMapper.connection.database_names
        for db in database
          if db.casecmp(params[:db]) == 0
            flash[:error] = "Database already exists in the system."
            render "explorer/index"
            return
          end
        end
        cl = Mongo::MongoClient.new
        database = cl.db('admin')
        database.command({:copydb => 1, :fromdb => current_database_name, :todb => params[:db]})
        current_database_name = params[:db]
        flash[:info] = "The database was copied successfully"
        redirect_to explorer_path(current_database_name)
        return
      end
    end
    
    render "explorer/index"
    return
  end

  def destroy
    if params.has_key?(:id)
      if !params[:id].empty?
        flash[:error]  = false
        database = MongoMapper.connection.database_names
        for db in database
          if db.casecmp(params[:id]) == 0
            MongoMapper.connection.drop_database(params[:id])
            current_database_name = ""
            current_database = ""
            flash[:info] = "The database was deleted successfully"
            redirect_to explorer_path(current_database_name)
            return
          end
        end
          flash[:error] = "The database has already been deleted."
        render "explorer/index"
      end
    end
    return
  end

  def create
    begin
      if params.has_key?(:db)
        if params[:db].empty?
          flash[:error] = "Database name can't be empty.."
          render "explorer/index"
          return
        elsif params[:db].match(/([\/\\\. $])/)
          flash[:error] = "Database name can't have invalid characters."
          render "explorer/index"
          return
        else
          flash[:error]  = false
          database = MongoMapper.connection.database_names
          for db in database
            if db.casecmp(params[:db]) == 0
              flash[:error] = "Database already exists in the system."
              render "explorer/index"
              return
            end
          end
          current_database  = Connection.new.db(params[:db])
          coll = current_database.collection('temp')   
          coll.remove
          current_database_name = params[:db]
          flash[:info] = "The database was added successfully"
          redirect_to explorer_path(current_database_name)
          return
        end
      end
    rescue Exception =>e
      flash[:error] = "There seems to be some issue. We shall get back to you shortly."
      render "explorer/index"
    end
  end

  protected
    def check_mongo_blacklist
      if current_database_name && !can_read_database?
        render "shared/blacklist"
        return
      end
      if current_collection_name && !can_read_collection?
        render "shared/collection_blacklist"
        return
      end
    end

    def require_edit_access
      if current_database_name && current_collection_name
        unless can_edit_collection?
          render "shared/collection_blacklist"
          return
        end
      elsif current_database_name
        unless can_edit_database?
          render "shared/blacklist"
          return
        end
      end
    end
  end

app/views/explorer/collections/show.html.erb
<% content_for :sidebar do %>
<%= render :partial => "shared/collections_sidebar" %>
<% end %>

<% if current_database.collection_names.include? current_collection_name %>
<% unless request.xhr? %>
<%= render :partial => "shared/collections_breadcrumbs" %>
<div class="page-header">
  <h3 class="di"><%= current_collection_name %></h3>
  <small><%= link_to "New Document", new_explorer_collection_document_path(current_database_name, current_collection_name), class: "btn pull-right" if can_edit? %></small>
</div>

<div class="collection-query">
  <form id="collection-form" name="query">
      <div class="interface">
        <div class="params">
          db.<%= current_collection_name %>.find(<span id="span-query" style>
          {
          <span id="query-input" spellcheck="false" contenteditable="true" data-type="hash" data-name="query">&#8203;</span>
          }
          </span><span id="span-fields" style="display: none;">
          , {
          <span id="fields-input" spellcheck="false" contenteditable="true" data-type="hash" data-name="fields">&#8203;</span>
          }
          </span>)<span id="span-sort" style="display: none;">
          .sort({
          <span id="sort-input" spellcheck="false" contenteditable="true" data-type="hash" data-name="sort">&#8203;</span>
          })
          </span><span id="span-skip" style="display: none;">
          .skip(
          <span id="skip-input" spellcheck="false" contenteditable="true" data-type="number" data-name="skip">&#8203;</span>
          )
          </span><span id="span-limit">
          .limit(
          <span id="limit-input" spellcheck="false" contenteditable="true" data-type="number" data-name="limit">25&#8203;</span>
          )
          </span><span id="span-explain" style="display: none;">
          .explain()
          </span>
      </div>
      <div class="buttons">
        <button id="fields" class="btn btn-inverse" data-field="fields">fields{}</button>
        <button id="sort" class="btn btn-inverse" data-field="sort">sort()</button>
        <button id="skip" class="btn btn-inverse" data-field="skip">skip()</button>
        <button id="explain" class="btn btn-inverse" data-field="explain">explain()</button>
        <div class="btn-group">
          <a id="languages" class="btn dropdown-toggle btn-inverse" data-toggle="dropdown" href="#">
          Language
          <span class="caret"></span>
        </a>
        <ul id="languages-dropdown" class="dropdown-menu">
          <li id="0"><a href="#">Show me in...</a></li>
          <li class="divider"></li>
          <li id="ruby"><a href="#">Ruby</a></li>
          <li id="python"><a href="#">Python</a></li>
          <li id="node"><a href="#">Node.JS</a></li>
        </ul>
      </div>
        <button id="submit" class="btn pull-right" type="submit">Query</button>
      </div>
    </div>
  </form>
</div>

<div id="languages-modal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 id="modal-language">Show me in...</h3>
  </div>
  <div class="modal-body">
    <textarea id="query"></textarea>
  </div>
  <div class="modal-footer">
    <button id="close" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

<%= javascript_tag do %>
var current_database_name = '<%=j current_database_name %>',
    current_collection_name = '<%=j current_collection_name %>';
<% end %>

<% end %>

<% if @explain %>
<div id="results">
  <%= debug @results.explain %>
</div>
<% else %>
<table id="results" class="table table-bordered">
  <% @results.each do |document| %>
  <tr>
    <td>
      <% if document.has_key?("_id") %>
      <%= link_to JSON.generate(JSON.parse(document.to_json), space: " ", indent: " "), explorer_collection_document_path(current_database_name, current_collection_name, document["_id"]) %>
      <% else %>
      <%= JSON.generate(JSON.parse(document.to_json), space: " ", indent: " ") %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>
    <%= link_to "Delete Collection", explorer_collection_path(current_database_name, current_collection_name), confirm: "Are you sure you want to delete the collection?", method: :delete, class: "btn btn-danger pull-right" unless request.xhr? %>
</div>

<% end %>

<% else %>
<div class="alert alert-error">
  <strong>Error!</strong>
  That collection doesn't exist, want to <%= link_to "create it?", "#" %>
</div>
<% end %>