config/routes.rb
MongoTools::Application.routes.draw do
  use_doorkeeper

  resources :explorer do
    scope :module => "explorer" do
      resources :collections, :except => [:new], :constraints => { :id => /.*/ } do
        resources :documents
      end
    end
  end

  get "/monitoring" => "monitoring#index"
  get "/monitoring/opcounts" => "monitoring#op_counts"

  get "/sharding" => "sharding#index"

  resources :query_analyzer, :only => [:index]
  root :to => redirect("/explorer")

  resource :server_status, :only => [:index, :show]

  resources :databases, :only => [:index, :show] do
    resource :sharding_stats, :only => [:index, :show]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MongoTools" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div id="top-navbar" class="navbar navbar-fluid-top navbar-static-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to image_tag("logo.png", alt: "MongoTools"), root_path, class: "brand" %>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li class="<%= params[:controller].start_with?("explorer") ? "active" : "" %>"><%= link_to "Explorer", explorer_index_path %></li>
              <li class="<%= params[:controller].start_with?("monitoring") ? "active" : "" %>"><%= link_to "Monitoring", monitoring_path %></li>
              <li class="<%= params[:controller].start_with?("sharding") ? "active" : "" %>"><%= link_to "Sharding", sharding_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <% if content_for?(:sidebar) %>
        <div class="span3">
          <%= yield(:sidebar) %>
        </div>
        <% end %>
        <div class="<%= content_for?(:sidebar) ? "span9" : "span12" %>">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

    <%= javascript_include_tag "application" %>
  </body>
</html>